CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE user (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK ( role IN ('ADM', 'CUSTOMER') )
)