CREATE TABLE route (
    id INTEGER PRIMARY KEY,
    employee_id INTEGER REFERENCES employee(id),
    status VARCHAR(20) NOT NULL CHECK ( status IN ('PENDENTE', 'EM_ANDAMENTO', 'ENCERRADO', 'CANCELADO') ),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)